### ISSUE TITLE
No response from the model

### ISSUE THREAD

**Issue by chedim** [NotPunchnox/rkllama#27]
Freshly installed rkllama, no responses from the model listed in your examples that I pulled with rkllama:

```
FROM: TinyLlama-1.1B-Chat-v1.0-rk3588-w8a8-opt-0-hybrid-ratio-0.5.rkllm
HuggingFace Path: punchnox/Tinnyllama-1.1B-rk3588-rkllm-1.1.4
```

<img width="868" alt="Image" src="https://github.com/user-attachments/assets/b4fab5cf-7076-4ced-88ee-6ea7c136fd20" />

Please advise?

**Comment by gonesurfing** [comment]
Same issue, Rock-5c with Armbian.

**Comment by malakraft** [comment]
Hello, got the same issue the other day, I noticed that my kernel didn't had NPU driver. Maybe try to see if drivers are install. 

Using that command: `sudo cat /sys/kernel/debug/rknpu/version`
Should output something like: `RKNPU driver: v0.9.7`

I initially install ubuntu-24.10 from Joshua-Riek (which didn't had NPU drivers). Had to pass to ubuntu-24.04 for RKLLAMA to work.

Hope it help

**Comment by Nurb4000** [comment]
> Same issue, Rock-5c with Armbian.

Last time i looked at stock Armbian it didn't have the RK drivers baked in.  Had to use a 'remix'  ( https://github.com/Pelochus/armbian-build-rknpu-updates )

**Comment by gonesurfing** [comment]
The Armbian kernel I'm on has the NPU driver included.
`Linux rock-5c 6.1.99-vendor-rk35xx #1 SMP Fri Feb  7 15:19:27 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

`sudo cat /sys/kernel/debug/rknpu/version`
`RKNPU driver: v0.9.8`

from dmesg:
`[drm] Initialized rknpu 0.9.8 20240828 for fdab0000.npu on minor 1`

**Comment by chedim** [comment]
Mine is rockchip-ubuntu 24.10

```
root@agatha:/home/chedim# uname -a
Linux agatha 6.1.0-1025-rockchip #25-Ubuntu SMP Mon Aug 26 23:01:14 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
root@agatha:/home/chedim# cat /sys/kernel/debug/rknpu/version
RKNPU driver: v0.9.7
root@agatha:/home/chedim# 
```

**Comment by chedim** [comment]
😿 anything I can do to help with this?

**Comment by RikudouGoku** [comment]
> The Armbian kernel I'm on has the NPU driver included. `Linux rock-5c 6.1.99-vendor-rk35xx #1 SMP Fri Feb 7 15:19:27 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`
> 
> `sudo cat /sys/kernel/debug/rknpu/version` `RKNPU driver: v0.9.8`


I also have the same exact RKNPU driver version although im on the Orange pi 5 plus.
Linux orangepi5-plus 6.1.99-vendor-rk35xx #1 SMP Wed Mar 19 11:16:36 UTC 2025 aarch64 GNU/Linux

I am using the docker installation though but exactly the same issue as OP has.


> from dmesg: `[drm] Initialized rknpu 0.9.8 20240828 for fdab0000.npu on minor 1`

How do I see this?

**Comment by RikudouGoku** [comment]
> 😿 anything I can do to help with this?
Here are the log for my container after just starting it.
rkllama-1  | Starting the environment with Miniconda3.
rkllama-1  | Processor: rk3588
rkllama-1  | RK3588 frequencies optimized for NPU inferencing
rkllama-1  | Setting the frequency for the rk3588 platform...
rkllama-1  | Initializing model mappings...
rkllama-1  | Start the API at http://localhost:8080
rkllama-1  |  * Serving Flask app 'server'
rkllama-1  |  * Debug mode: off
rkllama-1  | 2025-04-09 18:55:41,504 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
rkllama-1  |  * Running on all addresses (0.0.0.0)
rkllama-1  |  * Running on http://127.0.0.1:8080
rkllama-1  |  * Running on http://192.168.144.2:8080
rkllama-1  | 2025-04-09 18:55:41,505 - werkzeug - INFO - Press CTRL+C to quit

**Comment by RikudouGoku** [comment]
@chedim @gonesurfing I fixed it!

![Image](https://github.com/user-attachments/assets/73c698e1-9264-415c-b627-b0599d64bbc5)

I am not sure which of these 2 changes i made did this but here is the updated docker compose. I added the Devices section and changed the image.
(Got this from ChatGPT ironically.)
```
version: "3.8"
services:
  rkllama:
    container_name: rkllama
    image: ghcr.io/notpunchnox/rkllama:main
    privileged: true
    ports:
      - 11434:11434 # Ollama-compatible endpoint
    volumes:
      - /docker/rkllama/models:/root/RKLLAMA/models
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129 # NPU device
    restart: unless-stopped
```

As for why I changed the port, i did that due to ChatGPT:

> The port has changed from the default 8080:8080 to 11434:11434 because Ollama-compatible API on rkllama (the image you’re using) uses port 11434 for communication.
> 
> Here’s the reasoning behind it:
> 
> Default Ports:
> 
> 8080 is often used for web interfaces or services in many applications, but it can be used for any service.
> 
> RKLLAMA and Ollama Compatibility:
> 
> rkllama implements Ollama's API and listens on port 11434 by default for compatibility with Ollama clients.
> 
> This allows you to interact with the server using the standard Ollama API endpoints (/api/generate, /api/chat, etc.).
> 
> Why the Change:
> 
> The 11434 port is specifically chosen to avoid conflicts with other applications that may already be using port 8080.
> 
> It’s the port expected by most Ollama-compatible clients like Open WebUI.



This is the old compose I used that did not work for reference.
```
name: rkllm-server
services:
  rkllama:
    volumes:
      - /docker/rkllm-server/models:/root/RKLLAMA/models
    privileged: true
    ports:
      - 8091:8080
    image: thanhtantran/rkllama:arm64
```
